### PR TITLE
Update README with note about Bluez<=5.23

### PR DESCRIPTION
**Pull request by cal-id**

### CODE REVIEW

**Comment by larsblumberg** [comment]
Thanks for your suggestion. I however wouldn't expect BlueZ < 5.38 to work. Only with BlueZ 5.42 the 
experimental flag for the GATT D-Bus API has been removed. That's why the doc states:

> It is tested to work fine with BlueZ 5.44, slightly older versions should however work, too.

Your  comment would suggest that BlueZ starting at 5.24 would work with this SDK what I totally doubt.

**Comment by cal-id** [comment]
Perhaps add something along the lines of your reply then? 

Would be useful to qualify _slightly_ as I (naively) assumed it meant a major version.

**Comment by larsblumberg** [comment]
What about _It is tested to work fine with BlueZ 5.44, any release >= 5.38 should however work, too._ ?

**Comment by cal-id** [comment]
Seems clear to me!

**Comment by larsblumberg** [comment]
Hi @neelotpalnag, you want to merge it?

**Comment by neelotpalnag** [comment]
Sure! 
Merging & closing. Cheers @cal-id

**Pull request merged**
